#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso phaseModel
wmake libso interfacialModels
wmake libso kineticTheoryModels
wmake libso electrostaticsKTModels
wmake libso derivedChargeFvPatchFields 
wmake

# ----------------------------------------------------------------- end-of-file
